security:

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            access_denied_url: /login
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/event/edit, roles: ROLE_ADMIN}
        - { path: ^/event/delete, roles: ROLE_ADMIN}

