index:
  path: /
  controller: App\Controller\CredentialController::index

login:
  path: /login
  controller: App\Controller\CredentialController::login

registration:
  path: /registration
  controller: App\Controller\CredentialController::registration

logout:
  path: /logout
  controller: App\Controller\CredentialController::logout


create_event:
  path: /event/create
  controller: App\Controller\EventController::createEvent


create_review:
  path: /event/{eventId}/create_review
  controller: App\Controller\ReviewController::createReview