index:
  path: /
  controller: App\Controller\CredentialController::index

login:
  path: /login
  controller: App\Controller\CredentialController::login

registration:
  path: /registration
  controller: App\Controller\CredentialController::registration

logout:
  path: /logout
  controller: App\Controller\CredentialController::logout